// -*- js -*-
// Copyright © 2018 by Ezer IT Consulting. All rights reserved. E-mail: claus@ezer.dk

// Client-side handling of localization of the user interface.


//****************************************************************************************************
// Localization_general interface
//
// This data-only interface defines localized strings for the user interface. They correspond to the
// contents of the {PRE}language_LANG database table whose 'textgroup' field is 'js'. (Similar to
// the contents of the file myapp/language/langsrc/LANG/js_lang.php.)
//
interface Localization_general {
    [key : string] : string;   // Maps key => localized string
}

//****************************************************************************************************
// l10n_js variable
//
// Contains localized terms for the user interface.
// The variable is generated by the server code.
//
declare let l10n_js : Localization_general;


//****************************************************************************************************
// localize function
//
// Looks up a localized string.
//
// Parameter:
//     s: The key for the string.
// Returns:
//     The localized value of s.
//
function localize(s : string) {
    let str = l10n_js[s];

    return str===undefined ? '??' + s + '??' : str;
}
